### ISSUE TITLE
成绩页面手动刷新时，snackbar重复弹出

### ISSUE THREAD

**Issue by Iceberry-qdd** [CustedNG/CustedNG#14]
**问题描述**：手动刷新以往学期成绩时，无论刷新成功与否，底部的snackbar widget反复弹出，且弹出次数等于该学期与最新学期的相隔数。

**系统环境**：Android11,RealmeUI v2.0

**版本**：555(+59f)

**复现**：如上所述

**Comment by lollipopkit** [comment]
感谢反馈，已修复
commit：c98bccb
